spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/analysis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
#    data: classpath:data.sql
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info
    com.alexwang.blog: debug
  file: /tmp/analysis.log
app:
  default:
    user: ${APP_DEFAULT_USER:admin}        # Use environment variable or fallback to 'admin'
    password: ${APP_DEFAULT_PASSWORD:password}  # Use environment variable or fallback to 'password'
